package com.yechrom.cloud.dto.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BuyHouseExample {

    private Integer start;
    private Integer count;

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public BuyHouseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBuyOrderIsNull() {
            addCriterion("buy_order is null");
            return (Criteria) this;
        }

        public Criteria andBuyOrderIsNotNull() {
            addCriterion("buy_order is not null");
            return (Criteria) this;
        }

        public Criteria andBuyOrderEqualTo(String value) {
            addCriterion("buy_order =", value, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderNotEqualTo(String value) {
            addCriterion("buy_order <>", value, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderGreaterThan(String value) {
            addCriterion("buy_order >", value, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderGreaterThanOrEqualTo(String value) {
            addCriterion("buy_order >=", value, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderLessThan(String value) {
            addCriterion("buy_order <", value, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderLessThanOrEqualTo(String value) {
            addCriterion("buy_order <=", value, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderLike(String value) {
            addCriterion("buy_order like", value, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderNotLike(String value) {
            addCriterion("buy_order not like", value, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderIn(List<String> values) {
            addCriterion("buy_order in", values, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderNotIn(List<String> values) {
            addCriterion("buy_order not in", values, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderBetween(String value1, String value2) {
            addCriterion("buy_order between", value1, value2, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyOrderNotBetween(String value1, String value2) {
            addCriterion("buy_order not between", value1, value2, "buyOrder");
            return (Criteria) this;
        }

        public Criteria andBuyStatueIsNull() {
            addCriterion("buy_statue is null");
            return (Criteria) this;
        }

        public Criteria andBuyStatueIsNotNull() {
            addCriterion("buy_statue is not null");
            return (Criteria) this;
        }

        public Criteria andBuyStatueEqualTo(Integer value) {
            addCriterion("buy_statue =", value, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyStatueNotEqualTo(Integer value) {
            addCriterion("buy_statue <>", value, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyStatueGreaterThan(Integer value) {
            addCriterion("buy_statue >", value, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyStatueGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_statue >=", value, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyStatueLessThan(Integer value) {
            addCriterion("buy_statue <", value, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyStatueLessThanOrEqualTo(Integer value) {
            addCriterion("buy_statue <=", value, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyStatueIn(List<Integer> values) {
            addCriterion("buy_statue in", values, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyStatueNotIn(List<Integer> values) {
            addCriterion("buy_statue not in", values, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyStatueBetween(Integer value1, Integer value2) {
            addCriterion("buy_statue between", value1, value2, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyStatueNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_statue not between", value1, value2, "buyStatue");
            return (Criteria) this;
        }

        public Criteria andBuyTimeIsNull() {
            addCriterion("buy_time is null");
            return (Criteria) this;
        }

        public Criteria andBuyTimeIsNotNull() {
            addCriterion("buy_time is not null");
            return (Criteria) this;
        }

        public Criteria andBuyTimeEqualTo(Date value) {
            addCriterion("buy_time =", value, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyTimeNotEqualTo(Date value) {
            addCriterion("buy_time <>", value, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyTimeGreaterThan(Date value) {
            addCriterion("buy_time >", value, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("buy_time >=", value, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyTimeLessThan(Date value) {
            addCriterion("buy_time <", value, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyTimeLessThanOrEqualTo(Date value) {
            addCriterion("buy_time <=", value, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyTimeIn(List<Date> values) {
            addCriterion("buy_time in", values, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyTimeNotIn(List<Date> values) {
            addCriterion("buy_time not in", values, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyTimeBetween(Date value1, Date value2) {
            addCriterion("buy_time between", value1, value2, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyTimeNotBetween(Date value1, Date value2) {
            addCriterion("buy_time not between", value1, value2, "buyTime");
            return (Criteria) this;
        }

        public Criteria andBuyUuidIsNull() {
            addCriterion("buy_uuid is null");
            return (Criteria) this;
        }

        public Criteria andBuyUuidIsNotNull() {
            addCriterion("buy_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andBuyUuidEqualTo(String value) {
            addCriterion("buy_uuid =", value, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidNotEqualTo(String value) {
            addCriterion("buy_uuid <>", value, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidGreaterThan(String value) {
            addCriterion("buy_uuid >", value, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidGreaterThanOrEqualTo(String value) {
            addCriterion("buy_uuid >=", value, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidLessThan(String value) {
            addCriterion("buy_uuid <", value, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidLessThanOrEqualTo(String value) {
            addCriterion("buy_uuid <=", value, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidLike(String value) {
            addCriterion("buy_uuid like", value, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidNotLike(String value) {
            addCriterion("buy_uuid not like", value, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidIn(List<String> values) {
            addCriterion("buy_uuid in", values, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidNotIn(List<String> values) {
            addCriterion("buy_uuid not in", values, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidBetween(String value1, String value2) {
            addCriterion("buy_uuid between", value1, value2, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andBuyUuidNotBetween(String value1, String value2) {
            addCriterion("buy_uuid not between", value1, value2, "buyUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidIsNull() {
            addCriterion("sell_uuid is null");
            return (Criteria) this;
        }

        public Criteria andSellUuidIsNotNull() {
            addCriterion("sell_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andSellUuidEqualTo(String value) {
            addCriterion("sell_uuid =", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidNotEqualTo(String value) {
            addCriterion("sell_uuid <>", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidGreaterThan(String value) {
            addCriterion("sell_uuid >", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidGreaterThanOrEqualTo(String value) {
            addCriterion("sell_uuid >=", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidLessThan(String value) {
            addCriterion("sell_uuid <", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidLessThanOrEqualTo(String value) {
            addCriterion("sell_uuid <=", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidLike(String value) {
            addCriterion("sell_uuid like", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidNotLike(String value) {
            addCriterion("sell_uuid not like", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidIn(List<String> values) {
            addCriterion("sell_uuid in", values, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidNotIn(List<String> values) {
            addCriterion("sell_uuid not in", values, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidBetween(String value1, String value2) {
            addCriterion("sell_uuid between", value1, value2, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidNotBetween(String value1, String value2) {
            addCriterion("sell_uuid not between", value1, value2, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andBuyAddressIsNull() {
            addCriterion("buy_address is null");
            return (Criteria) this;
        }

        public Criteria andBuyAddressIsNotNull() {
            addCriterion("buy_address is not null");
            return (Criteria) this;
        }

        public Criteria andBuyAddressEqualTo(String value) {
            addCriterion("buy_address =", value, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressNotEqualTo(String value) {
            addCriterion("buy_address <>", value, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressGreaterThan(String value) {
            addCriterion("buy_address >", value, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("buy_address >=", value, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressLessThan(String value) {
            addCriterion("buy_address <", value, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressLessThanOrEqualTo(String value) {
            addCriterion("buy_address <=", value, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressLike(String value) {
            addCriterion("buy_address like", value, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressNotLike(String value) {
            addCriterion("buy_address not like", value, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressIn(List<String> values) {
            addCriterion("buy_address in", values, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressNotIn(List<String> values) {
            addCriterion("buy_address not in", values, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressBetween(String value1, String value2) {
            addCriterion("buy_address between", value1, value2, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyAddressNotBetween(String value1, String value2) {
            addCriterion("buy_address not between", value1, value2, "buyAddress");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionIsNull() {
            addCriterion("buy_introduction is null");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionIsNotNull() {
            addCriterion("buy_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionEqualTo(String value) {
            addCriterion("buy_introduction =", value, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionNotEqualTo(String value) {
            addCriterion("buy_introduction <>", value, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionGreaterThan(String value) {
            addCriterion("buy_introduction >", value, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("buy_introduction >=", value, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionLessThan(String value) {
            addCriterion("buy_introduction <", value, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionLessThanOrEqualTo(String value) {
            addCriterion("buy_introduction <=", value, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionLike(String value) {
            addCriterion("buy_introduction like", value, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionNotLike(String value) {
            addCriterion("buy_introduction not like", value, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionIn(List<String> values) {
            addCriterion("buy_introduction in", values, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionNotIn(List<String> values) {
            addCriterion("buy_introduction not in", values, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionBetween(String value1, String value2) {
            addCriterion("buy_introduction between", value1, value2, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyIntroductionNotBetween(String value1, String value2) {
            addCriterion("buy_introduction not between", value1, value2, "buyIntroduction");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIsNull() {
            addCriterion("buy_price is null");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIsNotNull() {
            addCriterion("buy_price is not null");
            return (Criteria) this;
        }

        public Criteria andBuyPriceEqualTo(Long value) {
            addCriterion("buy_price =", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotEqualTo(Long value) {
            addCriterion("buy_price <>", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceGreaterThan(Long value) {
            addCriterion("buy_price >", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("buy_price >=", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceLessThan(Long value) {
            addCriterion("buy_price <", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceLessThanOrEqualTo(Long value) {
            addCriterion("buy_price <=", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIn(List<Long> values) {
            addCriterion("buy_price in", values, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotIn(List<Long> values) {
            addCriterion("buy_price not in", values, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceBetween(Long value1, Long value2) {
            addCriterion("buy_price between", value1, value2, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotBetween(Long value1, Long value2) {
            addCriterion("buy_price not between", value1, value2, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPickIsNull() {
            addCriterion("buy_pick is null");
            return (Criteria) this;
        }

        public Criteria andBuyPickIsNotNull() {
            addCriterion("buy_pick is not null");
            return (Criteria) this;
        }

        public Criteria andBuyPickEqualTo(Integer value) {
            addCriterion("buy_pick =", value, "buyPick");
            return (Criteria) this;
        }

        public Criteria andBuyPickNotEqualTo(Integer value) {
            addCriterion("buy_pick <>", value, "buyPick");
            return (Criteria) this;
        }

        public Criteria andBuyPickGreaterThan(Integer value) {
            addCriterion("buy_pick >", value, "buyPick");
            return (Criteria) this;
        }

        public Criteria andBuyPickGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_pick >=", value, "buyPick");
            return (Criteria) this;
        }

        public Criteria andBuyPickLessThan(Integer value) {
            addCriterion("buy_pick <", value, "buyPick");
            return (Criteria) this;
        }

        public Criteria andBuyPickLessThanOrEqualTo(Integer value) {
            addCriterion("buy_pick <=", value, "buyPick");
            return (Criteria) this;
        }

        public Criteria andBuyPickIn(List<Integer> values) {
            addCriterion("buy_pick in", values, "buyPick");
            return (Criteria) this;
        }

        public Criteria andBuyPickNotIn(List<Integer> values) {
            addCriterion("buy_pick not in", values, "buyPick");
            return (Criteria) this;
        }

        public Criteria andBuyPickBetween(Integer value1, Integer value2) {
            addCriterion("buy_pick between", value1, value2, "buyPick");
            return (Criteria) this;
        }

        public Criteria andBuyPickNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_pick not between", value1, value2, "buyPick");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNull() {
            addCriterion("flag1 is null");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNotNull() {
            addCriterion("flag1 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag1EqualTo(String value) {
            addCriterion("flag1 =", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotEqualTo(String value) {
            addCriterion("flag1 <>", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThan(String value) {
            addCriterion("flag1 >", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThanOrEqualTo(String value) {
            addCriterion("flag1 >=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThan(String value) {
            addCriterion("flag1 <", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThanOrEqualTo(String value) {
            addCriterion("flag1 <=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1Like(String value) {
            addCriterion("flag1 like", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotLike(String value) {
            addCriterion("flag1 not like", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1In(List<String> values) {
            addCriterion("flag1 in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotIn(List<String> values) {
            addCriterion("flag1 not in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1Between(String value1, String value2) {
            addCriterion("flag1 between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotBetween(String value1, String value2) {
            addCriterion("flag1 not between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNull() {
            addCriterion("flag2 is null");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNotNull() {
            addCriterion("flag2 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag2EqualTo(String value) {
            addCriterion("flag2 =", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotEqualTo(String value) {
            addCriterion("flag2 <>", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThan(String value) {
            addCriterion("flag2 >", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThanOrEqualTo(String value) {
            addCriterion("flag2 >=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThan(String value) {
            addCriterion("flag2 <", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThanOrEqualTo(String value) {
            addCriterion("flag2 <=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2Like(String value) {
            addCriterion("flag2 like", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotLike(String value) {
            addCriterion("flag2 not like", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2In(List<String> values) {
            addCriterion("flag2 in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotIn(List<String> values) {
            addCriterion("flag2 not in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2Between(String value1, String value2) {
            addCriterion("flag2 between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotBetween(String value1, String value2) {
            addCriterion("flag2 not between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNull() {
            addCriterion("flag3 is null");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNotNull() {
            addCriterion("flag3 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag3EqualTo(String value) {
            addCriterion("flag3 =", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotEqualTo(String value) {
            addCriterion("flag3 <>", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThan(String value) {
            addCriterion("flag3 >", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThanOrEqualTo(String value) {
            addCriterion("flag3 >=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThan(String value) {
            addCriterion("flag3 <", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThanOrEqualTo(String value) {
            addCriterion("flag3 <=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3Like(String value) {
            addCriterion("flag3 like", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotLike(String value) {
            addCriterion("flag3 not like", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3In(List<String> values) {
            addCriterion("flag3 in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotIn(List<String> values) {
            addCriterion("flag3 not in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3Between(String value1, String value2) {
            addCriterion("flag3 between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotBetween(String value1, String value2) {
            addCriterion("flag3 not between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNull() {
            addCriterion("flag4 is null");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNotNull() {
            addCriterion("flag4 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag4EqualTo(String value) {
            addCriterion("flag4 =", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotEqualTo(String value) {
            addCriterion("flag4 <>", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThan(String value) {
            addCriterion("flag4 >", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThanOrEqualTo(String value) {
            addCriterion("flag4 >=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThan(String value) {
            addCriterion("flag4 <", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThanOrEqualTo(String value) {
            addCriterion("flag4 <=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4Like(String value) {
            addCriterion("flag4 like", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotLike(String value) {
            addCriterion("flag4 not like", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4In(List<String> values) {
            addCriterion("flag4 in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotIn(List<String> values) {
            addCriterion("flag4 not in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4Between(String value1, String value2) {
            addCriterion("flag4 between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotBetween(String value1, String value2) {
            addCriterion("flag4 not between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNull() {
            addCriterion("flag5 is null");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNotNull() {
            addCriterion("flag5 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag5EqualTo(String value) {
            addCriterion("flag5 =", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotEqualTo(String value) {
            addCriterion("flag5 <>", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThan(String value) {
            addCriterion("flag5 >", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThanOrEqualTo(String value) {
            addCriterion("flag5 >=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThan(String value) {
            addCriterion("flag5 <", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThanOrEqualTo(String value) {
            addCriterion("flag5 <=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5Like(String value) {
            addCriterion("flag5 like", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotLike(String value) {
            addCriterion("flag5 not like", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5In(List<String> values) {
            addCriterion("flag5 in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotIn(List<String> values) {
            addCriterion("flag5 not in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5Between(String value1, String value2) {
            addCriterion("flag5 between", value1, value2, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotBetween(String value1, String value2) {
            addCriterion("flag5 not between", value1, value2, "flag5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buy_house
     *
     * @mbggenerated do_not_delete_during_merge Sat Jan 25 10:16:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}