package com.yechrom.cloud.dto.pojo;

import java.util.Date;

public class BuyHouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.buy_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String buyOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.buy_statue
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer buyStatue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.buy_time
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Date buyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.buy_uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String buyUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.sell_uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String sellUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.buy_address
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String buyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.buy_introduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String buyIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.buy_price
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Long buyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.buy_pick
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer buyPick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_house.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.buy_order
     *
     * @return the value of buy_house.buy_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getBuyOrder() {
        return buyOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.buy_order
     *
     * @param buyOrder the value for buy_house.buy_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setBuyOrder(String buyOrder) {
        this.buyOrder = buyOrder == null ? null : buyOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.buy_statue
     *
     * @return the value of buy_house.buy_statue
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getBuyStatue() {
        return buyStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.buy_statue
     *
     * @param buyStatue the value for buy_house.buy_statue
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setBuyStatue(Integer buyStatue) {
        this.buyStatue = buyStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.buy_time
     *
     * @return the value of buy_house.buy_time
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.buy_time
     *
     * @param buyTime the value for buy_house.buy_time
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.buy_uuid
     *
     * @return the value of buy_house.buy_uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getBuyUuid() {
        return buyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.buy_uuid
     *
     * @param buyUuid the value for buy_house.buy_uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setBuyUuid(String buyUuid) {
        this.buyUuid = buyUuid == null ? null : buyUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.sell_uuid
     *
     * @return the value of buy_house.sell_uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getSellUuid() {
        return sellUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.sell_uuid
     *
     * @param sellUuid the value for buy_house.sell_uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellUuid(String sellUuid) {
        this.sellUuid = sellUuid == null ? null : sellUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.buy_address
     *
     * @return the value of buy_house.buy_address
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getBuyAddress() {
        return buyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.buy_address
     *
     * @param buyAddress the value for buy_house.buy_address
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setBuyAddress(String buyAddress) {
        this.buyAddress = buyAddress == null ? null : buyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.buy_introduction
     *
     * @return the value of buy_house.buy_introduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getBuyIntroduction() {
        return buyIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.buy_introduction
     *
     * @param buyIntroduction the value for buy_house.buy_introduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setBuyIntroduction(String buyIntroduction) {
        this.buyIntroduction = buyIntroduction == null ? null : buyIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.buy_price
     *
     * @return the value of buy_house.buy_price
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Long getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.buy_price
     *
     * @param buyPrice the value for buy_house.buy_price
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setBuyPrice(Long buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.buy_pick
     *
     * @return the value of buy_house.buy_pick
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getBuyPick() {
        return buyPick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.buy_pick
     *
     * @param buyPick the value for buy_house.buy_pick
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setBuyPick(Integer buyPick) {
        this.buyPick = buyPick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.is_delete
     *
     * @return the value of buy_house.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.is_delete
     *
     * @param isDelete the value for buy_house.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.flag1
     *
     * @return the value of buy_house.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag1() {
        return flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.flag1
     *
     * @param flag1 the value for buy_house.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag1(String flag1) {
        this.flag1 = flag1 == null ? null : flag1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.flag2
     *
     * @return the value of buy_house.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.flag2
     *
     * @param flag2 the value for buy_house.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2 == null ? null : flag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.flag3
     *
     * @return the value of buy_house.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag3() {
        return flag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.flag3
     *
     * @param flag3 the value for buy_house.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag3(String flag3) {
        this.flag3 = flag3 == null ? null : flag3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.flag4
     *
     * @return the value of buy_house.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag4() {
        return flag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.flag4
     *
     * @param flag4 the value for buy_house.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag4(String flag4) {
        this.flag4 = flag4 == null ? null : flag4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_house.flag5
     *
     * @return the value of buy_house.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag5() {
        return flag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_house.flag5
     *
     * @param flag5 the value for buy_house.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag5(String flag5) {
        this.flag5 = flag5 == null ? null : flag5.trim();
    }
}