package com.yechrom.cloud.dto.pojo;

import java.util.Date;

public class QuestionOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.ques_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String quesOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.ques_statue
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer quesStatue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.ques_time
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Date quesTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.ques_address
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String quesAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.ques_intruduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String quesIntruduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.ques_seller
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String quesSeller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.ques_user
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String quesUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.ques_order
     *
     * @return the value of question_order.ques_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getQuesOrder() {
        return quesOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.ques_order
     *
     * @param quesOrder the value for question_order.ques_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setQuesOrder(String quesOrder) {
        this.quesOrder = quesOrder == null ? null : quesOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.ques_statue
     *
     * @return the value of question_order.ques_statue
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getQuesStatue() {
        return quesStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.ques_statue
     *
     * @param quesStatue the value for question_order.ques_statue
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setQuesStatue(Integer quesStatue) {
        this.quesStatue = quesStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.ques_time
     *
     * @return the value of question_order.ques_time
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Date getQuesTime() {
        return quesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.ques_time
     *
     * @param quesTime the value for question_order.ques_time
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setQuesTime(Date quesTime) {
        this.quesTime = quesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.ques_address
     *
     * @return the value of question_order.ques_address
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getQuesAddress() {
        return quesAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.ques_address
     *
     * @param quesAddress the value for question_order.ques_address
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setQuesAddress(String quesAddress) {
        this.quesAddress = quesAddress == null ? null : quesAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.ques_intruduction
     *
     * @return the value of question_order.ques_intruduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getQuesIntruduction() {
        return quesIntruduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.ques_intruduction
     *
     * @param quesIntruduction the value for question_order.ques_intruduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setQuesIntruduction(String quesIntruduction) {
        this.quesIntruduction = quesIntruduction == null ? null : quesIntruduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.ques_seller
     *
     * @return the value of question_order.ques_seller
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getQuesSeller() {
        return quesSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.ques_seller
     *
     * @param quesSeller the value for question_order.ques_seller
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setQuesSeller(String quesSeller) {
        this.quesSeller = quesSeller == null ? null : quesSeller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.ques_user
     *
     * @return the value of question_order.ques_user
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getQuesUser() {
        return quesUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.ques_user
     *
     * @param quesUser the value for question_order.ques_user
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setQuesUser(String quesUser) {
        this.quesUser = quesUser == null ? null : quesUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.is_delete
     *
     * @return the value of question_order.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.is_delete
     *
     * @param isDelete the value for question_order.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.flag1
     *
     * @return the value of question_order.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag1() {
        return flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.flag1
     *
     * @param flag1 the value for question_order.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag1(String flag1) {
        this.flag1 = flag1 == null ? null : flag1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.flag2
     *
     * @return the value of question_order.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.flag2
     *
     * @param flag2 the value for question_order.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2 == null ? null : flag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.flag3
     *
     * @return the value of question_order.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag3() {
        return flag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.flag3
     *
     * @param flag3 the value for question_order.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag3(String flag3) {
        this.flag3 = flag3 == null ? null : flag3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.flag4
     *
     * @return the value of question_order.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag4() {
        return flag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.flag4
     *
     * @param flag4 the value for question_order.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag4(String flag4) {
        this.flag4 = flag4 == null ? null : flag4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order.flag5
     *
     * @return the value of question_order.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag5() {
        return flag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order.flag5
     *
     * @param flag5 the value for question_order.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag5(String flag5) {
        this.flag5 = flag5 == null ? null : flag5.trim();
    }
}