package com.yechrom.cloud.dto.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuestionOrderExample {

    private Integer start;
    private Integer count;

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public QuestionOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuesOrderIsNull() {
            addCriterion("ques_order is null");
            return (Criteria) this;
        }

        public Criteria andQuesOrderIsNotNull() {
            addCriterion("ques_order is not null");
            return (Criteria) this;
        }

        public Criteria andQuesOrderEqualTo(String value) {
            addCriterion("ques_order =", value, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderNotEqualTo(String value) {
            addCriterion("ques_order <>", value, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderGreaterThan(String value) {
            addCriterion("ques_order >", value, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderGreaterThanOrEqualTo(String value) {
            addCriterion("ques_order >=", value, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderLessThan(String value) {
            addCriterion("ques_order <", value, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderLessThanOrEqualTo(String value) {
            addCriterion("ques_order <=", value, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderLike(String value) {
            addCriterion("ques_order like", value, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderNotLike(String value) {
            addCriterion("ques_order not like", value, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderIn(List<String> values) {
            addCriterion("ques_order in", values, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderNotIn(List<String> values) {
            addCriterion("ques_order not in", values, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderBetween(String value1, String value2) {
            addCriterion("ques_order between", value1, value2, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesOrderNotBetween(String value1, String value2) {
            addCriterion("ques_order not between", value1, value2, "quesOrder");
            return (Criteria) this;
        }

        public Criteria andQuesStatueIsNull() {
            addCriterion("ques_statue is null");
            return (Criteria) this;
        }

        public Criteria andQuesStatueIsNotNull() {
            addCriterion("ques_statue is not null");
            return (Criteria) this;
        }

        public Criteria andQuesStatueEqualTo(Integer value) {
            addCriterion("ques_statue =", value, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesStatueNotEqualTo(Integer value) {
            addCriterion("ques_statue <>", value, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesStatueGreaterThan(Integer value) {
            addCriterion("ques_statue >", value, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesStatueGreaterThanOrEqualTo(Integer value) {
            addCriterion("ques_statue >=", value, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesStatueLessThan(Integer value) {
            addCriterion("ques_statue <", value, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesStatueLessThanOrEqualTo(Integer value) {
            addCriterion("ques_statue <=", value, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesStatueIn(List<Integer> values) {
            addCriterion("ques_statue in", values, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesStatueNotIn(List<Integer> values) {
            addCriterion("ques_statue not in", values, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesStatueBetween(Integer value1, Integer value2) {
            addCriterion("ques_statue between", value1, value2, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesStatueNotBetween(Integer value1, Integer value2) {
            addCriterion("ques_statue not between", value1, value2, "quesStatue");
            return (Criteria) this;
        }

        public Criteria andQuesTimeIsNull() {
            addCriterion("ques_time is null");
            return (Criteria) this;
        }

        public Criteria andQuesTimeIsNotNull() {
            addCriterion("ques_time is not null");
            return (Criteria) this;
        }

        public Criteria andQuesTimeEqualTo(Date value) {
            addCriterion("ques_time =", value, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesTimeNotEqualTo(Date value) {
            addCriterion("ques_time <>", value, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesTimeGreaterThan(Date value) {
            addCriterion("ques_time >", value, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ques_time >=", value, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesTimeLessThan(Date value) {
            addCriterion("ques_time <", value, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesTimeLessThanOrEqualTo(Date value) {
            addCriterion("ques_time <=", value, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesTimeIn(List<Date> values) {
            addCriterion("ques_time in", values, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesTimeNotIn(List<Date> values) {
            addCriterion("ques_time not in", values, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesTimeBetween(Date value1, Date value2) {
            addCriterion("ques_time between", value1, value2, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesTimeNotBetween(Date value1, Date value2) {
            addCriterion("ques_time not between", value1, value2, "quesTime");
            return (Criteria) this;
        }

        public Criteria andQuesAddressIsNull() {
            addCriterion("ques_address is null");
            return (Criteria) this;
        }

        public Criteria andQuesAddressIsNotNull() {
            addCriterion("ques_address is not null");
            return (Criteria) this;
        }

        public Criteria andQuesAddressEqualTo(String value) {
            addCriterion("ques_address =", value, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressNotEqualTo(String value) {
            addCriterion("ques_address <>", value, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressGreaterThan(String value) {
            addCriterion("ques_address >", value, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ques_address >=", value, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressLessThan(String value) {
            addCriterion("ques_address <", value, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressLessThanOrEqualTo(String value) {
            addCriterion("ques_address <=", value, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressLike(String value) {
            addCriterion("ques_address like", value, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressNotLike(String value) {
            addCriterion("ques_address not like", value, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressIn(List<String> values) {
            addCriterion("ques_address in", values, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressNotIn(List<String> values) {
            addCriterion("ques_address not in", values, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressBetween(String value1, String value2) {
            addCriterion("ques_address between", value1, value2, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesAddressNotBetween(String value1, String value2) {
            addCriterion("ques_address not between", value1, value2, "quesAddress");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionIsNull() {
            addCriterion("ques_intruduction is null");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionIsNotNull() {
            addCriterion("ques_intruduction is not null");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionEqualTo(String value) {
            addCriterion("ques_intruduction =", value, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionNotEqualTo(String value) {
            addCriterion("ques_intruduction <>", value, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionGreaterThan(String value) {
            addCriterion("ques_intruduction >", value, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionGreaterThanOrEqualTo(String value) {
            addCriterion("ques_intruduction >=", value, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionLessThan(String value) {
            addCriterion("ques_intruduction <", value, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionLessThanOrEqualTo(String value) {
            addCriterion("ques_intruduction <=", value, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionLike(String value) {
            addCriterion("ques_intruduction like", value, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionNotLike(String value) {
            addCriterion("ques_intruduction not like", value, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionIn(List<String> values) {
            addCriterion("ques_intruduction in", values, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionNotIn(List<String> values) {
            addCriterion("ques_intruduction not in", values, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionBetween(String value1, String value2) {
            addCriterion("ques_intruduction between", value1, value2, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesIntruductionNotBetween(String value1, String value2) {
            addCriterion("ques_intruduction not between", value1, value2, "quesIntruduction");
            return (Criteria) this;
        }

        public Criteria andQuesSellerIsNull() {
            addCriterion("ques_seller is null");
            return (Criteria) this;
        }

        public Criteria andQuesSellerIsNotNull() {
            addCriterion("ques_seller is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSellerEqualTo(String value) {
            addCriterion("ques_seller =", value, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerNotEqualTo(String value) {
            addCriterion("ques_seller <>", value, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerGreaterThan(String value) {
            addCriterion("ques_seller >", value, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerGreaterThanOrEqualTo(String value) {
            addCriterion("ques_seller >=", value, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerLessThan(String value) {
            addCriterion("ques_seller <", value, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerLessThanOrEqualTo(String value) {
            addCriterion("ques_seller <=", value, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerLike(String value) {
            addCriterion("ques_seller like", value, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerNotLike(String value) {
            addCriterion("ques_seller not like", value, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerIn(List<String> values) {
            addCriterion("ques_seller in", values, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerNotIn(List<String> values) {
            addCriterion("ques_seller not in", values, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerBetween(String value1, String value2) {
            addCriterion("ques_seller between", value1, value2, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesSellerNotBetween(String value1, String value2) {
            addCriterion("ques_seller not between", value1, value2, "quesSeller");
            return (Criteria) this;
        }

        public Criteria andQuesUserIsNull() {
            addCriterion("ques_user is null");
            return (Criteria) this;
        }

        public Criteria andQuesUserIsNotNull() {
            addCriterion("ques_user is not null");
            return (Criteria) this;
        }

        public Criteria andQuesUserEqualTo(String value) {
            addCriterion("ques_user =", value, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserNotEqualTo(String value) {
            addCriterion("ques_user <>", value, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserGreaterThan(String value) {
            addCriterion("ques_user >", value, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserGreaterThanOrEqualTo(String value) {
            addCriterion("ques_user >=", value, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserLessThan(String value) {
            addCriterion("ques_user <", value, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserLessThanOrEqualTo(String value) {
            addCriterion("ques_user <=", value, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserLike(String value) {
            addCriterion("ques_user like", value, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserNotLike(String value) {
            addCriterion("ques_user not like", value, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserIn(List<String> values) {
            addCriterion("ques_user in", values, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserNotIn(List<String> values) {
            addCriterion("ques_user not in", values, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserBetween(String value1, String value2) {
            addCriterion("ques_user between", value1, value2, "quesUser");
            return (Criteria) this;
        }

        public Criteria andQuesUserNotBetween(String value1, String value2) {
            addCriterion("ques_user not between", value1, value2, "quesUser");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNull() {
            addCriterion("flag1 is null");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNotNull() {
            addCriterion("flag1 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag1EqualTo(String value) {
            addCriterion("flag1 =", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotEqualTo(String value) {
            addCriterion("flag1 <>", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThan(String value) {
            addCriterion("flag1 >", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThanOrEqualTo(String value) {
            addCriterion("flag1 >=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThan(String value) {
            addCriterion("flag1 <", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThanOrEqualTo(String value) {
            addCriterion("flag1 <=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1Like(String value) {
            addCriterion("flag1 like", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotLike(String value) {
            addCriterion("flag1 not like", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1In(List<String> values) {
            addCriterion("flag1 in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotIn(List<String> values) {
            addCriterion("flag1 not in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1Between(String value1, String value2) {
            addCriterion("flag1 between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotBetween(String value1, String value2) {
            addCriterion("flag1 not between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNull() {
            addCriterion("flag2 is null");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNotNull() {
            addCriterion("flag2 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag2EqualTo(String value) {
            addCriterion("flag2 =", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotEqualTo(String value) {
            addCriterion("flag2 <>", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThan(String value) {
            addCriterion("flag2 >", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThanOrEqualTo(String value) {
            addCriterion("flag2 >=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThan(String value) {
            addCriterion("flag2 <", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThanOrEqualTo(String value) {
            addCriterion("flag2 <=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2Like(String value) {
            addCriterion("flag2 like", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotLike(String value) {
            addCriterion("flag2 not like", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2In(List<String> values) {
            addCriterion("flag2 in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotIn(List<String> values) {
            addCriterion("flag2 not in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2Between(String value1, String value2) {
            addCriterion("flag2 between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotBetween(String value1, String value2) {
            addCriterion("flag2 not between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNull() {
            addCriterion("flag3 is null");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNotNull() {
            addCriterion("flag3 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag3EqualTo(String value) {
            addCriterion("flag3 =", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotEqualTo(String value) {
            addCriterion("flag3 <>", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThan(String value) {
            addCriterion("flag3 >", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThanOrEqualTo(String value) {
            addCriterion("flag3 >=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThan(String value) {
            addCriterion("flag3 <", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThanOrEqualTo(String value) {
            addCriterion("flag3 <=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3Like(String value) {
            addCriterion("flag3 like", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotLike(String value) {
            addCriterion("flag3 not like", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3In(List<String> values) {
            addCriterion("flag3 in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotIn(List<String> values) {
            addCriterion("flag3 not in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3Between(String value1, String value2) {
            addCriterion("flag3 between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotBetween(String value1, String value2) {
            addCriterion("flag3 not between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNull() {
            addCriterion("flag4 is null");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNotNull() {
            addCriterion("flag4 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag4EqualTo(String value) {
            addCriterion("flag4 =", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotEqualTo(String value) {
            addCriterion("flag4 <>", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThan(String value) {
            addCriterion("flag4 >", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThanOrEqualTo(String value) {
            addCriterion("flag4 >=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThan(String value) {
            addCriterion("flag4 <", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThanOrEqualTo(String value) {
            addCriterion("flag4 <=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4Like(String value) {
            addCriterion("flag4 like", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotLike(String value) {
            addCriterion("flag4 not like", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4In(List<String> values) {
            addCriterion("flag4 in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotIn(List<String> values) {
            addCriterion("flag4 not in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4Between(String value1, String value2) {
            addCriterion("flag4 between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotBetween(String value1, String value2) {
            addCriterion("flag4 not between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNull() {
            addCriterion("flag5 is null");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNotNull() {
            addCriterion("flag5 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag5EqualTo(String value) {
            addCriterion("flag5 =", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotEqualTo(String value) {
            addCriterion("flag5 <>", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThan(String value) {
            addCriterion("flag5 >", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThanOrEqualTo(String value) {
            addCriterion("flag5 >=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThan(String value) {
            addCriterion("flag5 <", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThanOrEqualTo(String value) {
            addCriterion("flag5 <=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5Like(String value) {
            addCriterion("flag5 like", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotLike(String value) {
            addCriterion("flag5 not like", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5In(List<String> values) {
            addCriterion("flag5 in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotIn(List<String> values) {
            addCriterion("flag5 not in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5Between(String value1, String value2) {
            addCriterion("flag5 between", value1, value2, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotBetween(String value1, String value2) {
            addCriterion("flag5 not between", value1, value2, "flag5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question_order
     *
     * @mbggenerated do_not_delete_during_merge Sat Jan 25 10:16:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}