package com.yechrom.cloud.dto.pojo;

import java.util.Date;

public class SellHouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.sell_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String sellOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.sell_statue
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer sellStatue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.sell_time
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Date sellTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.sell_uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String sellUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.sell_address
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String sellAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.sell_imgs
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String sellImgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.sell_introduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String sellIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.sell_price
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Long sellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.buy_user
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String buyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.sell_pick
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer sellPick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_house.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.sell_order
     *
     * @return the value of sell_house.sell_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getSellOrder() {
        return sellOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.sell_order
     *
     * @param sellOrder the value for sell_house.sell_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellOrder(String sellOrder) {
        this.sellOrder = sellOrder == null ? null : sellOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.sell_statue
     *
     * @return the value of sell_house.sell_statue
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getSellStatue() {
        return sellStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.sell_statue
     *
     * @param sellStatue the value for sell_house.sell_statue
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellStatue(Integer sellStatue) {
        this.sellStatue = sellStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.sell_time
     *
     * @return the value of sell_house.sell_time
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Date getSellTime() {
        return sellTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.sell_time
     *
     * @param sellTime the value for sell_house.sell_time
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellTime(Date sellTime) {
        this.sellTime = sellTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.sell_uuid
     *
     * @return the value of sell_house.sell_uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getSellUuid() {
        return sellUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.sell_uuid
     *
     * @param sellUuid the value for sell_house.sell_uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellUuid(String sellUuid) {
        this.sellUuid = sellUuid == null ? null : sellUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.sell_address
     *
     * @return the value of sell_house.sell_address
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getSellAddress() {
        return sellAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.sell_address
     *
     * @param sellAddress the value for sell_house.sell_address
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellAddress(String sellAddress) {
        this.sellAddress = sellAddress == null ? null : sellAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.sell_imgs
     *
     * @return the value of sell_house.sell_imgs
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getSellImgs() {
        return sellImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.sell_imgs
     *
     * @param sellImgs the value for sell_house.sell_imgs
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellImgs(String sellImgs) {
        this.sellImgs = sellImgs == null ? null : sellImgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.sell_introduction
     *
     * @return the value of sell_house.sell_introduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getSellIntroduction() {
        return sellIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.sell_introduction
     *
     * @param sellIntroduction the value for sell_house.sell_introduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellIntroduction(String sellIntroduction) {
        this.sellIntroduction = sellIntroduction == null ? null : sellIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.sell_price
     *
     * @return the value of sell_house.sell_price
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Long getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.sell_price
     *
     * @param sellPrice the value for sell_house.sell_price
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellPrice(Long sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.buy_user
     *
     * @return the value of sell_house.buy_user
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getBuyUser() {
        return buyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.buy_user
     *
     * @param buyUser the value for sell_house.buy_user
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setBuyUser(String buyUser) {
        this.buyUser = buyUser == null ? null : buyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.sell_pick
     *
     * @return the value of sell_house.sell_pick
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getSellPick() {
        return sellPick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.sell_pick
     *
     * @param sellPick the value for sell_house.sell_pick
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setSellPick(Integer sellPick) {
        this.sellPick = sellPick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.is_delete
     *
     * @return the value of sell_house.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.is_delete
     *
     * @param isDelete the value for sell_house.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.flag1
     *
     * @return the value of sell_house.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag1() {
        return flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.flag1
     *
     * @param flag1 the value for sell_house.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag1(String flag1) {
        this.flag1 = flag1 == null ? null : flag1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.flag2
     *
     * @return the value of sell_house.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.flag2
     *
     * @param flag2 the value for sell_house.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2 == null ? null : flag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.flag3
     *
     * @return the value of sell_house.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag3() {
        return flag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.flag3
     *
     * @param flag3 the value for sell_house.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag3(String flag3) {
        this.flag3 = flag3 == null ? null : flag3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.flag4
     *
     * @return the value of sell_house.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag4() {
        return flag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.flag4
     *
     * @param flag4 the value for sell_house.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag4(String flag4) {
        this.flag4 = flag4 == null ? null : flag4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_house.flag5
     *
     * @return the value of sell_house.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag5() {
        return flag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_house.flag5
     *
     * @param flag5 the value for sell_house.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag5(String flag5) {
        this.flag5 = flag5 == null ? null : flag5.trim();
    }
}