package com.yechrom.cloud.dto.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SellHouseExample {

    @Override
    public String toString() {
        return "SellHouseExample{" +
                "start=" + start +
                ", count=" + count +
                ", orderByClause='" + orderByClause + '\'' +
                ", distinct=" + distinct +
                ", oredCriteria=" + oredCriteria +
                '}';
    }

    private Integer start;
    private Integer count;

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public SellHouseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSellOrderIsNull() {
            addCriterion("sell_order is null");
            return (Criteria) this;
        }

        public Criteria andSellOrderIsNotNull() {
            addCriterion("sell_order is not null");
            return (Criteria) this;
        }

        public Criteria andSellOrderEqualTo(String value) {
            addCriterion("sell_order =", value, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderNotEqualTo(String value) {
            addCriterion("sell_order <>", value, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderGreaterThan(String value) {
            addCriterion("sell_order >", value, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderGreaterThanOrEqualTo(String value) {
            addCriterion("sell_order >=", value, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderLessThan(String value) {
            addCriterion("sell_order <", value, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderLessThanOrEqualTo(String value) {
            addCriterion("sell_order <=", value, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderLike(String value) {
            addCriterion("sell_order like", value, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderNotLike(String value) {
            addCriterion("sell_order not like", value, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderIn(List<String> values) {
            addCriterion("sell_order in", values, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderNotIn(List<String> values) {
            addCriterion("sell_order not in", values, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderBetween(String value1, String value2) {
            addCriterion("sell_order between", value1, value2, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellOrderNotBetween(String value1, String value2) {
            addCriterion("sell_order not between", value1, value2, "sellOrder");
            return (Criteria) this;
        }

        public Criteria andSellStatueIsNull() {
            addCriterion("sell_statue is null");
            return (Criteria) this;
        }

        public Criteria andSellStatueIsNotNull() {
            addCriterion("sell_statue is not null");
            return (Criteria) this;
        }

        public Criteria andSellStatueEqualTo(Integer value) {
            addCriterion("sell_statue =", value, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellStatueNotEqualTo(Integer value) {
            addCriterion("sell_statue <>", value, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellStatueGreaterThan(Integer value) {
            addCriterion("sell_statue >", value, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellStatueGreaterThanOrEqualTo(Integer value) {
            addCriterion("sell_statue >=", value, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellStatueLessThan(Integer value) {
            addCriterion("sell_statue <", value, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellStatueLessThanOrEqualTo(Integer value) {
            addCriterion("sell_statue <=", value, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellStatueIn(List<Integer> values) {
            addCriterion("sell_statue in", values, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellStatueNotIn(List<Integer> values) {
            addCriterion("sell_statue not in", values, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellStatueBetween(Integer value1, Integer value2) {
            addCriterion("sell_statue between", value1, value2, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellStatueNotBetween(Integer value1, Integer value2) {
            addCriterion("sell_statue not between", value1, value2, "sellStatue");
            return (Criteria) this;
        }

        public Criteria andSellTimeIsNull() {
            addCriterion("sell_time is null");
            return (Criteria) this;
        }

        public Criteria andSellTimeIsNotNull() {
            addCriterion("sell_time is not null");
            return (Criteria) this;
        }

        public Criteria andSellTimeEqualTo(Date value) {
            addCriterion("sell_time =", value, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellTimeNotEqualTo(Date value) {
            addCriterion("sell_time <>", value, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellTimeGreaterThan(Date value) {
            addCriterion("sell_time >", value, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sell_time >=", value, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellTimeLessThan(Date value) {
            addCriterion("sell_time <", value, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellTimeLessThanOrEqualTo(Date value) {
            addCriterion("sell_time <=", value, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellTimeIn(List<Date> values) {
            addCriterion("sell_time in", values, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellTimeNotIn(List<Date> values) {
            addCriterion("sell_time not in", values, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellTimeBetween(Date value1, Date value2) {
            addCriterion("sell_time between", value1, value2, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellTimeNotBetween(Date value1, Date value2) {
            addCriterion("sell_time not between", value1, value2, "sellTime");
            return (Criteria) this;
        }

        public Criteria andSellUuidIsNull() {
            addCriterion("sell_uuid is null");
            return (Criteria) this;
        }

        public Criteria andSellUuidIsNotNull() {
            addCriterion("sell_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andSellUuidEqualTo(String value) {
            addCriterion("sell_uuid =", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidNotEqualTo(String value) {
            addCriterion("sell_uuid <>", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidGreaterThan(String value) {
            addCriterion("sell_uuid >", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidGreaterThanOrEqualTo(String value) {
            addCriterion("sell_uuid >=", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidLessThan(String value) {
            addCriterion("sell_uuid <", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidLessThanOrEqualTo(String value) {
            addCriterion("sell_uuid <=", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidLike(String value) {
            addCriterion("sell_uuid like", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidNotLike(String value) {
            addCriterion("sell_uuid not like", value, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidIn(List<String> values) {
            addCriterion("sell_uuid in", values, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidNotIn(List<String> values) {
            addCriterion("sell_uuid not in", values, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidBetween(String value1, String value2) {
            addCriterion("sell_uuid between", value1, value2, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellUuidNotBetween(String value1, String value2) {
            addCriterion("sell_uuid not between", value1, value2, "sellUuid");
            return (Criteria) this;
        }

        public Criteria andSellAddressIsNull() {
            addCriterion("sell_address is null");
            return (Criteria) this;
        }

        public Criteria andSellAddressIsNotNull() {
            addCriterion("sell_address is not null");
            return (Criteria) this;
        }

        public Criteria andSellAddressEqualTo(String value) {
            addCriterion("sell_address =", value, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressNotEqualTo(String value) {
            addCriterion("sell_address <>", value, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressGreaterThan(String value) {
            addCriterion("sell_address >", value, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressGreaterThanOrEqualTo(String value) {
            addCriterion("sell_address >=", value, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressLessThan(String value) {
            addCriterion("sell_address <", value, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressLessThanOrEqualTo(String value) {
            addCriterion("sell_address <=", value, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressLike(String value) {
            addCriterion("sell_address like", value, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressNotLike(String value) {
            addCriterion("sell_address not like", value, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressIn(List<String> values) {
            addCriterion("sell_address in", values, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressNotIn(List<String> values) {
            addCriterion("sell_address not in", values, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressBetween(String value1, String value2) {
            addCriterion("sell_address between", value1, value2, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellAddressNotBetween(String value1, String value2) {
            addCriterion("sell_address not between", value1, value2, "sellAddress");
            return (Criteria) this;
        }

        public Criteria andSellImgsIsNull() {
            addCriterion("sell_imgs is null");
            return (Criteria) this;
        }

        public Criteria andSellImgsIsNotNull() {
            addCriterion("sell_imgs is not null");
            return (Criteria) this;
        }

        public Criteria andSellImgsEqualTo(String value) {
            addCriterion("sell_imgs =", value, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsNotEqualTo(String value) {
            addCriterion("sell_imgs <>", value, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsGreaterThan(String value) {
            addCriterion("sell_imgs >", value, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsGreaterThanOrEqualTo(String value) {
            addCriterion("sell_imgs >=", value, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsLessThan(String value) {
            addCriterion("sell_imgs <", value, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsLessThanOrEqualTo(String value) {
            addCriterion("sell_imgs <=", value, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsLike(String value) {
            addCriterion("sell_imgs like", value, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsNotLike(String value) {
            addCriterion("sell_imgs not like", value, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsIn(List<String> values) {
            addCriterion("sell_imgs in", values, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsNotIn(List<String> values) {
            addCriterion("sell_imgs not in", values, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsBetween(String value1, String value2) {
            addCriterion("sell_imgs between", value1, value2, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellImgsNotBetween(String value1, String value2) {
            addCriterion("sell_imgs not between", value1, value2, "sellImgs");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionIsNull() {
            addCriterion("sell_introduction is null");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionIsNotNull() {
            addCriterion("sell_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionEqualTo(String value) {
            addCriterion("sell_introduction =", value, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionNotEqualTo(String value) {
            addCriterion("sell_introduction <>", value, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionGreaterThan(String value) {
            addCriterion("sell_introduction >", value, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("sell_introduction >=", value, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionLessThan(String value) {
            addCriterion("sell_introduction <", value, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionLessThanOrEqualTo(String value) {
            addCriterion("sell_introduction <=", value, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionLike(String value) {
            addCriterion("sell_introduction like", value, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionNotLike(String value) {
            addCriterion("sell_introduction not like", value, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionIn(List<String> values) {
            addCriterion("sell_introduction in", values, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionNotIn(List<String> values) {
            addCriterion("sell_introduction not in", values, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionBetween(String value1, String value2) {
            addCriterion("sell_introduction between", value1, value2, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellIntroductionNotBetween(String value1, String value2) {
            addCriterion("sell_introduction not between", value1, value2, "sellIntroduction");
            return (Criteria) this;
        }

        public Criteria andSellPriceIsNull() {
            addCriterion("sell_price is null");
            return (Criteria) this;
        }

        public Criteria andSellPriceIsNotNull() {
            addCriterion("sell_price is not null");
            return (Criteria) this;
        }

        public Criteria andSellPriceEqualTo(Long value) {
            addCriterion("sell_price =", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceNotEqualTo(Long value) {
            addCriterion("sell_price <>", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceGreaterThan(Long value) {
            addCriterion("sell_price >", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("sell_price >=", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceLessThan(Long value) {
            addCriterion("sell_price <", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceLessThanOrEqualTo(Long value) {
            addCriterion("sell_price <=", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceIn(List<Long> values) {
            addCriterion("sell_price in", values, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceNotIn(List<Long> values) {
            addCriterion("sell_price not in", values, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceBetween(Long value1, Long value2) {
            addCriterion("sell_price between", value1, value2, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceNotBetween(Long value1, Long value2) {
            addCriterion("sell_price not between", value1, value2, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andBuyUserIsNull() {
            addCriterion("buy_user is null");
            return (Criteria) this;
        }

        public Criteria andBuyUserIsNotNull() {
            addCriterion("buy_user is not null");
            return (Criteria) this;
        }

        public Criteria andBuyUserEqualTo(String value) {
            addCriterion("buy_user =", value, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserNotEqualTo(String value) {
            addCriterion("buy_user <>", value, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserGreaterThan(String value) {
            addCriterion("buy_user >", value, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserGreaterThanOrEqualTo(String value) {
            addCriterion("buy_user >=", value, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserLessThan(String value) {
            addCriterion("buy_user <", value, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserLessThanOrEqualTo(String value) {
            addCriterion("buy_user <=", value, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserLike(String value) {
            addCriterion("buy_user like", value, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserNotLike(String value) {
            addCriterion("buy_user not like", value, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserIn(List<String> values) {
            addCriterion("buy_user in", values, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserNotIn(List<String> values) {
            addCriterion("buy_user not in", values, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserBetween(String value1, String value2) {
            addCriterion("buy_user between", value1, value2, "buyUser");
            return (Criteria) this;
        }

        public Criteria andBuyUserNotBetween(String value1, String value2) {
            addCriterion("buy_user not between", value1, value2, "buyUser");
            return (Criteria) this;
        }

        public Criteria andSellPickIsNull() {
            addCriterion("sell_pick is null");
            return (Criteria) this;
        }

        public Criteria andSellPickIsNotNull() {
            addCriterion("sell_pick is not null");
            return (Criteria) this;
        }

        public Criteria andSellPickEqualTo(Integer value) {
            addCriterion("sell_pick =", value, "sellPick");
            return (Criteria) this;
        }

        public Criteria andSellPickNotEqualTo(Integer value) {
            addCriterion("sell_pick <>", value, "sellPick");
            return (Criteria) this;
        }

        public Criteria andSellPickGreaterThan(Integer value) {
            addCriterion("sell_pick >", value, "sellPick");
            return (Criteria) this;
        }

        public Criteria andSellPickGreaterThanOrEqualTo(Integer value) {
            addCriterion("sell_pick >=", value, "sellPick");
            return (Criteria) this;
        }

        public Criteria andSellPickLessThan(Integer value) {
            addCriterion("sell_pick <", value, "sellPick");
            return (Criteria) this;
        }

        public Criteria andSellPickLessThanOrEqualTo(Integer value) {
            addCriterion("sell_pick <=", value, "sellPick");
            return (Criteria) this;
        }

        public Criteria andSellPickIn(List<Integer> values) {
            addCriterion("sell_pick in", values, "sellPick");
            return (Criteria) this;
        }

        public Criteria andSellPickNotIn(List<Integer> values) {
            addCriterion("sell_pick not in", values, "sellPick");
            return (Criteria) this;
        }

        public Criteria andSellPickBetween(Integer value1, Integer value2) {
            addCriterion("sell_pick between", value1, value2, "sellPick");
            return (Criteria) this;
        }

        public Criteria andSellPickNotBetween(Integer value1, Integer value2) {
            addCriterion("sell_pick not between", value1, value2, "sellPick");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNull() {
            addCriterion("flag1 is null");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNotNull() {
            addCriterion("flag1 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag1EqualTo(String value) {
            addCriterion("flag1 =", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotEqualTo(String value) {
            addCriterion("flag1 <>", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThan(String value) {
            addCriterion("flag1 >", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThanOrEqualTo(String value) {
            addCriterion("flag1 >=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThan(String value) {
            addCriterion("flag1 <", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThanOrEqualTo(String value) {
            addCriterion("flag1 <=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1Like(String value) {
            addCriterion("flag1 like", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotLike(String value) {
            addCriterion("flag1 not like", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1In(List<String> values) {
            addCriterion("flag1 in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotIn(List<String> values) {
            addCriterion("flag1 not in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1Between(String value1, String value2) {
            addCriterion("flag1 between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotBetween(String value1, String value2) {
            addCriterion("flag1 not between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNull() {
            addCriterion("flag2 is null");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNotNull() {
            addCriterion("flag2 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag2EqualTo(String value) {
            addCriterion("flag2 =", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotEqualTo(String value) {
            addCriterion("flag2 <>", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThan(String value) {
            addCriterion("flag2 >", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThanOrEqualTo(String value) {
            addCriterion("flag2 >=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThan(String value) {
            addCriterion("flag2 <", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThanOrEqualTo(String value) {
            addCriterion("flag2 <=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2Like(String value) {
            addCriterion("flag2 like", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotLike(String value) {
            addCriterion("flag2 not like", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2In(List<String> values) {
            addCriterion("flag2 in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotIn(List<String> values) {
            addCriterion("flag2 not in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2Between(String value1, String value2) {
            addCriterion("flag2 between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotBetween(String value1, String value2) {
            addCriterion("flag2 not between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNull() {
            addCriterion("flag3 is null");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNotNull() {
            addCriterion("flag3 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag3EqualTo(String value) {
            addCriterion("flag3 =", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotEqualTo(String value) {
            addCriterion("flag3 <>", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThan(String value) {
            addCriterion("flag3 >", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThanOrEqualTo(String value) {
            addCriterion("flag3 >=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThan(String value) {
            addCriterion("flag3 <", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThanOrEqualTo(String value) {
            addCriterion("flag3 <=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3Like(String value) {
            addCriterion("flag3 like", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotLike(String value) {
            addCriterion("flag3 not like", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3In(List<String> values) {
            addCriterion("flag3 in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotIn(List<String> values) {
            addCriterion("flag3 not in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3Between(String value1, String value2) {
            addCriterion("flag3 between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotBetween(String value1, String value2) {
            addCriterion("flag3 not between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNull() {
            addCriterion("flag4 is null");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNotNull() {
            addCriterion("flag4 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag4EqualTo(String value) {
            addCriterion("flag4 =", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotEqualTo(String value) {
            addCriterion("flag4 <>", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThan(String value) {
            addCriterion("flag4 >", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThanOrEqualTo(String value) {
            addCriterion("flag4 >=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThan(String value) {
            addCriterion("flag4 <", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThanOrEqualTo(String value) {
            addCriterion("flag4 <=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4Like(String value) {
            addCriterion("flag4 like", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotLike(String value) {
            addCriterion("flag4 not like", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4In(List<String> values) {
            addCriterion("flag4 in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotIn(List<String> values) {
            addCriterion("flag4 not in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4Between(String value1, String value2) {
            addCriterion("flag4 between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotBetween(String value1, String value2) {
            addCriterion("flag4 not between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNull() {
            addCriterion("flag5 is null");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNotNull() {
            addCriterion("flag5 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag5EqualTo(String value) {
            addCriterion("flag5 =", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotEqualTo(String value) {
            addCriterion("flag5 <>", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThan(String value) {
            addCriterion("flag5 >", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThanOrEqualTo(String value) {
            addCriterion("flag5 >=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThan(String value) {
            addCriterion("flag5 <", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThanOrEqualTo(String value) {
            addCriterion("flag5 <=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5Like(String value) {
            addCriterion("flag5 like", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotLike(String value) {
            addCriterion("flag5 not like", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5In(List<String> values) {
            addCriterion("flag5 in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotIn(List<String> values) {
            addCriterion("flag5 not in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5Between(String value1, String value2) {
            addCriterion("flag5 between", value1, value2, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotBetween(String value1, String value2) {
            addCriterion("flag5 not between", value1, value2, "flag5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sell_house
     *
     * @mbggenerated do_not_delete_during_merge Sat Jan 25 10:16:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sell_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}