package com.yechrom.cloud.dto.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.roles
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer roles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.introduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avater
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String avater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    private String flag5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uuid
     *
     * @return the value of user.uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uuid
     *
     * @param uuid the value for user.uuid
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.roles
     *
     * @return the value of user.roles
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.roles
     *
     * @param roles the value for user.roles
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setRoles(Integer roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.introduction
     *
     * @return the value of user.introduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.introduction
     *
     * @param introduction the value for user.introduction
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avater
     *
     * @return the value of user.avater
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getAvater() {
        return avater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avater
     *
     * @param avater the value for user.avater
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setAvater(String avater) {
        this.avater = avater == null ? null : avater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_delete
     *
     * @return the value of user.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_delete
     *
     * @param isDelete the value for user.is_delete
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.flag1
     *
     * @return the value of user.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag1() {
        return flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.flag1
     *
     * @param flag1 the value for user.flag1
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag1(String flag1) {
        this.flag1 = flag1 == null ? null : flag1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.flag2
     *
     * @return the value of user.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.flag2
     *
     * @param flag2 the value for user.flag2
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2 == null ? null : flag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.flag3
     *
     * @return the value of user.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag3() {
        return flag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.flag3
     *
     * @param flag3 the value for user.flag3
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag3(String flag3) {
        this.flag3 = flag3 == null ? null : flag3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.flag4
     *
     * @return the value of user.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag4() {
        return flag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.flag4
     *
     * @param flag4 the value for user.flag4
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag4(String flag4) {
        this.flag4 = flag4 == null ? null : flag4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.flag5
     *
     * @return the value of user.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public String getFlag5() {
        return flag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.flag5
     *
     * @param flag5 the value for user.flag5
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    public void setFlag5(String flag5) {
        this.flag5 = flag5 == null ? null : flag5.trim();
    }


    @Override
    public String toString() {
        return "User{" +
                "uuid='" + uuid + '\'' +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", name='" + name + '\'' +
                ", roles=" + roles +
                ", introduction='" + introduction + '\'' +
                ", avater='" + avater + '\'' +
                ", isDelete=" + isDelete +
                ", flag1='" + flag1 + '\'' +
                ", flag2='" + flag2 + '\'' +
                ", flag3='" + flag3 + '\'' +
                ", flag4='" + flag4 + '\'' +
                ", flag5='" + flag5 + '\'' +
                '}';
    }
}