package com.yechrom.cloud.dto.mapper;

import com.yechrom.cloud.dto.pojo.BuyHouse;
import com.yechrom.cloud.dto.pojo.BuyHouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int countByExample(BuyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int deleteByExample(BuyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int deleteByPrimaryKey(String buyOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int insert(BuyHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int insertSelective(BuyHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    List<BuyHouse> selectByExample(BuyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    BuyHouse selectByPrimaryKey(String buyOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") BuyHouse record, @Param("example") BuyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int updateByExample(@Param("record") BuyHouse record, @Param("example") BuyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int updateByPrimaryKeySelective(BuyHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_house
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int updateByPrimaryKey(BuyHouse record);
}