package com.yechrom.cloud.dto.mapper;

import com.yechrom.cloud.dto.pojo.QuestionOrder;
import com.yechrom.cloud.dto.pojo.QuestionOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int countByExample(QuestionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int deleteByExample(QuestionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int deleteByPrimaryKey(String quesOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int insert(QuestionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int insertSelective(QuestionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    List<QuestionOrder> selectByExample(QuestionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    QuestionOrder selectByPrimaryKey(String quesOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") QuestionOrder record, @Param("example") QuestionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int updateByExample(@Param("record") QuestionOrder record, @Param("example") QuestionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int updateByPrimaryKeySelective(QuestionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_order
     *
     * @mbggenerated Sat Jan 25 10:16:00 CST 2020
     */
    int updateByPrimaryKey(QuestionOrder record);
}